services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    container_name: bot_service
    env_file:
      - .env
    depends_on:
      - api
    restart: always